import logging
from datetime import datetime, timezone
from zoneinfo import ZoneInfo

from apscheduler.schedulers.background import BackgroundScheduler
from sqlmodel import Session, select

from app.calendars.sync import sync_source
from app.config import get_settings
from app.db import engine
from app.devices import PANEL_DEVICE_ID, screen_state
from app.models import CalendarSource, Device
from app.photos.index import reindex
from app.sse import broadcaster
from app.comets import refresh_comet_elements
from app.weather.client import refresh_weather

logger = logging.getLogger(__name__)
settings = get_settings()
scheduler = BackgroundScheduler(timezone="UTC")


# ICS feeds are regenerated by the provider on its own schedule, so polling
# them faster changes nothing - the file we fetch is already stale at the
# source. CalDAV and Google report changes as they happen, so they get their
# own, much faster job.
SLOW_KINDS = ("ics",)
FAST_KINDS = ("caldav", "google")

# The panel is a browser tab that stays open for months, so it needs a
# positive signal that the stream is still alive. sse-starlette's own ping
# cannot serve: it is an SSE *comment*, which EventSource never surfaces to
# an addEventListener, so the page cannot tell a healthy quiet stream from a
# wedged one. This is a real named event for that reason.
HEARTBEAT_SECONDS = 30


def sync_kinds(kinds: tuple[str, ...]) -> None:
    with Session(engine) as session:
        sources = session.exec(
            select(CalendarSource).where(
                CalendarSource.kind.in_(kinds),
                CalendarSource.enabled == True,  # noqa: E712
            )
        ).all()
        changed = False
        for source in sources:
            try:
                if sync_source(session, source):
                    changed = True
            except Exception:
                # Roll back before moving on: sync_source deletes a source's
                # rows before rebuilding them, so a failure part-way through
                # leaves those deletes pending in the session. Without this,
                # the *next* source's successful commit would flush them and
                # silently empty the calendar that failed.
                session.rollback()
                logger.exception("Sync failed for source %s (%s)", source.id, source.url)
        if changed:
            broadcaster.publish("events.updated")


def run_slow_sync() -> None:
    sync_kinds(SLOW_KINDS)


def run_fast_sync() -> None:
    sync_kinds(FAST_KINDS)


def screen_status(session: Session) -> str:
    """Whether the panel's screen should be lit, as "on" or "off".

    Reuses the same screen_state the Pi's agent polls, so the browser and the
    agent can never disagree about whether it is bedtime.
    """
    device = session.get(Device, PANEL_DEVICE_ID)
    if device is None:
        return "on"
    now = datetime.now(timezone.utc)
    return screen_state(device, now, ZoneInfo(settings.home_timezone))["state"]


def heartbeat_data() -> dict:
    """The server's date, clock, and screen state, as the panel receives them.

    Separate from the job that publishes it because the stream route sends one
    on connect too - a panel that has just loaded should not have to wait up
    to a full interval to learn what time it is, or whether it is meant to be
    dark.
    """
    now = datetime.now(ZoneInfo(settings.home_timezone))
    try:
        with Session(engine) as session:
            screen = screen_status(session)
    except Exception:
        # "on" is the fail-safe answer: a panel showing the calendar when it
        # could have been dark is a much smaller problem than a panel that
        # blacks itself out because a query failed.
        logger.exception("Could not read the screen schedule for the heartbeat")
        screen = "on"
    return {"today": now.date().isoformat(), "now": now.isoformat(), "screen": screen}


def run_heartbeat() -> None:
    """Tell the panel the stream is alive, what day it is, and whether it
    should be showing anything at all.

    Carrying the date is what keeps an always-on panel from getting stuck on
    yesterday. events.updated only fires when a sync actually changes
    something, so on a quiet day nothing else would ever prompt a re-render and
    the "Today" heading would silently rot. Sending the server's date rather
    than letting the browser read its own clock keeps the panel's OS timezone
    out of it, the same way format.ts and /api/calendar already do.

    The screen state rides along for the screensaver, which must not start
    while the schedule says the display is meant to be dark. It goes here
    rather than the browser polling /api/devices/1/screen because that endpoint
    writes last_seen as a side effect, and last_seen means "the screen agent is
    alive" - two different clients writing it would blur that. The heartbeat
    already arrives on exactly the cadence the agent polls at.
    """
    broadcaster.publish("heartbeat", heartbeat_data())


def run_comet_refresh() -> None:
    """Pull the MPC's comet elements. Slow, remote, and entirely optional.

    Once a day is generous: these are orbits, and a newly discovered comet
    takes weeks to become worth looking at. A failure leaves the cached file
    alone, so the panel keeps showing whatever it last knew rather than going
    blank because a web server was busy.
    """
    if not settings.comets_enabled:
        return
    try:
        if refresh_comet_elements():
            broadcaster.publish("weather.updated")
    except Exception:
        logger.exception("Comet element refresh failed")


def run_photo_index() -> None:
    """Rescan the photo folder.

    This is the backstop, not the fast path: the filesystem observer in
    main.py picks up a dropped-in photo within seconds. It exists because
    inotify sees nothing when a folder is filled from the far side of an SMB
    or NFS mount, which is how a /photos share is very often populated.
    """
    try:
        with Session(engine) as session:
            if reindex(session):
                broadcaster.publish("photos.updated")
    except Exception:
        logger.exception("Photo index failed")


def run_weather_refresh() -> None:
    try:
        if refresh_weather():
            broadcaster.publish("weather.updated")
    except Exception:
        logger.exception("Weather refresh failed")


def start_scheduler() -> None:
    scheduler.add_job(
        run_slow_sync,
        "interval",
        minutes=settings.ics_poll_interval_minutes,
        id="ics_sync",
        next_run_time=datetime.now(),
    )
    scheduler.add_job(
        run_fast_sync,
        "interval",
        minutes=settings.fast_poll_interval_minutes,
        id="fast_sync",
        next_run_time=datetime.now(),
    )
    scheduler.add_job(
        run_heartbeat,
        "interval",
        seconds=HEARTBEAT_SECONDS,
        id="heartbeat",
        next_run_time=datetime.now(),
    )
    if settings.comets_enabled:
        scheduler.add_job(
            run_comet_refresh,
            "interval",
            hours=settings.comet_refresh_hours,
            id="comet_refresh",
            next_run_time=datetime.now(),
        )
    scheduler.add_job(
        run_photo_index,
        "interval",
        minutes=settings.photo_index_interval_minutes,
        id="photo_index",
        next_run_time=datetime.now(),
    )
    scheduler.add_job(
        run_weather_refresh,
        "interval",
        minutes=settings.weather_cache_minutes,
        id="weather_refresh",
        next_run_time=datetime.now(),
    )
    scheduler.start()


def stop_scheduler() -> None:
    scheduler.shutdown(wait=False)
