import logging
from datetime import datetime
from zoneinfo import ZoneInfo

from apscheduler.schedulers.background import BackgroundScheduler
from sqlmodel import Session, select

from app.calendars.sync import sync_source
from app.config import get_settings
from app.db import engine
from app.models import CalendarSource
from app.sse import broadcaster
from app.weather.client import refresh_weather

logger = logging.getLogger(__name__)
settings = get_settings()
scheduler = BackgroundScheduler(timezone="UTC")


# ICS feeds are regenerated by the provider on its own schedule, so polling
# them faster changes nothing - the file we fetch is already stale at the
# source. CalDAV and Google report changes as they happen, so they get their
# own, much faster job.
SLOW_KINDS = ("ics",)
FAST_KINDS = ("caldav", "google")

# The panel is a browser tab that stays open for months, so it needs a
# positive signal that the stream is still alive. sse-starlette's own ping
# cannot serve: it is an SSE *comment*, which EventSource never surfaces to
# an addEventListener, so the page cannot tell a healthy quiet stream from a
# wedged one. This is a real named event for that reason.
HEARTBEAT_SECONDS = 30


def sync_kinds(kinds: tuple[str, ...]) -> None:
    with Session(engine) as session:
        sources = session.exec(
            select(CalendarSource).where(
                CalendarSource.kind.in_(kinds),
                CalendarSource.enabled == True,  # noqa: E712
            )
        ).all()
        changed = False
        for source in sources:
            try:
                if sync_source(session, source):
                    changed = True
            except Exception:
                # Roll back before moving on: sync_source deletes a source's
                # rows before rebuilding them, so a failure part-way through
                # leaves those deletes pending in the session. Without this,
                # the *next* source's successful commit would flush them and
                # silently empty the calendar that failed.
                session.rollback()
                logger.exception("Sync failed for source %s (%s)", source.id, source.url)
        if changed:
            broadcaster.publish("events.updated")


def run_slow_sync() -> None:
    sync_kinds(SLOW_KINDS)


def run_fast_sync() -> None:
    sync_kinds(FAST_KINDS)


def heartbeat_data() -> dict:
    """The server's date and clock, as the panel receives them.

    Separate from the job that publishes it because the stream route sends one
    on connect too - a panel that has just loaded should not have to wait up
    to a full interval to learn what time it is.
    """
    now = datetime.now(ZoneInfo(settings.home_timezone))
    return {"today": now.date().isoformat(), "now": now.isoformat()}


def run_heartbeat() -> None:
    """Tell the panel the stream is alive, and what day it is.

    Carrying the date is what keeps an always-on panel from getting stuck on
    yesterday. events.updated only fires when a sync actually changes
    something, so on a quiet day nothing else would ever prompt a re-render and
    the "Today" heading would silently rot. Sending the server's date rather
    than letting the browser read its own clock keeps the panel's OS timezone
    out of it, the same way format.ts and /api/calendar already do.
    """
    broadcaster.publish("heartbeat", heartbeat_data())


def run_weather_refresh() -> None:
    try:
        if refresh_weather():
            broadcaster.publish("weather.updated")
    except Exception:
        logger.exception("Weather refresh failed")


def start_scheduler() -> None:
    scheduler.add_job(
        run_slow_sync,
        "interval",
        minutes=settings.ics_poll_interval_minutes,
        id="ics_sync",
        next_run_time=datetime.now(),
    )
    scheduler.add_job(
        run_fast_sync,
        "interval",
        minutes=settings.fast_poll_interval_minutes,
        id="fast_sync",
        next_run_time=datetime.now(),
    )
    scheduler.add_job(
        run_heartbeat,
        "interval",
        seconds=HEARTBEAT_SECONDS,
        id="heartbeat",
        next_run_time=datetime.now(),
    )
    scheduler.add_job(
        run_weather_refresh,
        "interval",
        minutes=settings.weather_cache_minutes,
        id="weather_refresh",
        next_run_time=datetime.now(),
    )
    scheduler.start()


def stop_scheduler() -> None:
    scheduler.shutdown(wait=False)
